# Generated by Django 3.2.5 on 2021-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
